# Generated by Django 4.1.9 on 2023-05-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_truyen_author_name_truyen_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='truyen',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
