# Generated by Django 4.1.9 on 2023-05-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_truyen_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truyen',
            name='img',
            field=models.ImageField(upload_to='truyen/'),
        ),
    ]
