# Generated by Django 4.1.9 on 2023-05-26 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0004_alter_truyen_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='truyen_category',
            old_name='truyen',
            new_name='Truyen',
        ),
        migrations.AddField(
            model_name='truyen',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='favorate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.truyen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=200)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('truyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.truyen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
