# Generated by Django 4.1.9 on 2023-05-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_comment_truyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='truyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.truyen'),
        ),
    ]
