# Generated by Django 4.1.9 on 2023-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_comment_truyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
