# Generated by Django 4.1.9 on 2023-05-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_comment_commenter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_name',
            new_name='comment_name',
        ),
    ]
