# Generated by Django 4.1.9 on 2023-05-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_rename_commenter_name_comment_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
