# Generated by Django 4.1.9 on 2023-05-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_remove_comment_comment_name_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
